### ISSUE TITLE
Sugestões

### ISSUE THREAD

**Issue by sergiors** [totalvoice/TotalVoiceAPI-PHP#2]
Funções como `debugOff` e `debugOn` poderia ter nomes indicando o que fazem, `turnDebugOff` e `turnDebugOn`, pois `debugOn`parece mais um resposta (`if (true === $foo->debugOff()) {`).

Sei que existe a necessidade e não ter depndencia por causa da galera que ta em sistema sem gerenciador de pacotes entao impossibilita usar um guzzle da vida, mas na parte q usa o curl poderia ser uma outra classe com uma abstração melhor, assim reforma SRP e fica mais facil dar manutenção, além de poder já no construtor ver se tem curl e lanção uma exception adequada.

```
$tts['mensagem'] = 'lendo texto 222';
$tts['velocidade'] = -2;
$dados_tts['acao'] = 'tts';
$dados_tts['acao_dados'] = $tts;
array_push($dados, $dados_tts);
```

um pequeno objeto POPO ajudaria a ter certeza q não terá um indice com erro, evitando erros para user land

**Comment by dilowagner** [comment]
Olá @sergiors! Obrigado pelas sugestões!

**Comment by dilowagner** [comment]
Olá @sergiors,
Lançamos outra versão da Lib que pode ser instalada via composer... confere lá.

https://github.com/totalvoice/totalvoice-php
