### ISSUE TITLE
Construtor errado

### ISSUE THREAD

**Issue by silasrm** [totalvoice/TotalVoiceAPI-PHP#3]
Salve,

A bastante tempo o PHP depreciou o construtor como um método com o mesmo nome da classe e vocês estão utilizando assim bizarramente.

Além de usar var para propriedades. Isso são coisas de PHP 4.

Arrumem isso!

**Comment by dilowagner** [comment]
Olá @silasrm ! Obrigado pelas sugestões, estamos atualizando nossas libs.... valeuuu!

**Comment by silasrm** [comment]
De nada, espero que melhorem ai!

**Comment by dilowagner** [comment]
Olá @silasrm
Lançamos outra versão da Lib que pode ser instalada via composer... confere lá.

https://github.com/totalvoice/totalvoice-php
